### ISSUE TITLE
/placechest crash server

### ISSUE THREAD

**Issue by PetteriM1** [Tee7even/Presents#7]
#### Issue description
/placechest crash server

#### Steps to reproduce the issue
Use /placechest in game

#### Versions
* Presents version: 1.5
* Nukkit version: 1.1.3

**Comment by karpovichv** [comment]
Sorry, but the plugin is no more maintained. That means, since Nukkit's API changes very often, it won't work with the newer versions... :(
But anyone is free to make a fork and update it. If someone will update it, one can contact me at nukkit.ru/nukkit.io, so I can pass the resource on the forums (or at least think of some options).
